// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk459tvzWrY2Cjt_mytdvaAkSwkBhULDo',
    appId: '1:550211871196:android:79b343806bd6d487fbaf19',
    messagingSenderId: '550211871196',
    projectId: 'fir-chat-3b365',
    databaseURL: 'https://fir-chat-3b365-default-rtdb.firebaseio.com',
    storageBucket: 'fir-chat-3b365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuZfhGUPvqJ2ofK3Qo1-MNECpXoUW1kyg',
    appId: '1:550211871196:ios:093fbbda22ba3224fbaf19',
    messagingSenderId: '550211871196',
    projectId: 'fir-chat-3b365',
    databaseURL: 'https://fir-chat-3b365-default-rtdb.firebaseio.com',
    storageBucket: 'fir-chat-3b365.appspot.com',
    androidClientId: '550211871196-ddggjmlcfi4345cn0qolshppsubt3u3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
